#!/usr/bin/env node

import { writeFileSync } from 'fs';
import { resolve } from 'path';

const SEP_META = [
  { num: 10, title: 'Stellar Web Authentication', status: 'Active', url: 'https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md' },
  { num: 24, title: 'Hosted Deposit and Withdrawal', status: 'Active', url: 'https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md' },
  { num: 29, title: 'Network Passphrase', status: 'Active', url: 'https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0029.md' },
  { num: 38, title: 'Anchor RFQ', status: 'Active', url: 'https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md' },
  { num: 41, title: 'Soroban Smart Contracts', status: 'Active', url: 'https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0041.md' },
];

const table = [
  '| SEP | Title | Status | Link |',
  '|-----|-------|--------|------|',
  ...SEP_META.map(s =>
    `| ${s.num} | ${s.title} | ${s.status} | [Spec](${s.url}) |`
  ),
].join('\n');

const doc = `# Auto-generated SEP Reference\n\n> Generated by \`scripts/fetch-seps.mjs\`\n\n${table}\n`;

writeFileSync(resolve(import.meta.dirname, '../website/docs/seps-reference.md'), doc);
console.log('Generated seps-reference.md');
